In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

## Load the training data into feature matrix, class labels, and event ids:

In [2]:
from proj1_helpers import *
from helpers import *

DATA_TRAIN_PATH = '../train.csv' 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)
y[y==-1]=0

In [3]:
ys, tXs = y, tX

In [4]:
tXs,_,_= standardize(tXs)

In [5]:
#Optional: normalize rows
row_sums = tXs.max(axis=1)
tXs = tXs / row_sums[:, np.newaxis]

In [6]:
tXs.shape

(250000, 31)

In [7]:
ys.shape

(250000,)

In [8]:
ys

array([ 1.,  0.,  0., ...,  1.,  0.,  0.])

# Crazy Machine Learning

## Baselines (all methods should get similar estimates of w and mse)

## Fit with Least squares

In [9]:
from least_squares import least_squares
from least_squares import least_squares_GD_auto, least_squares_SGD_simple
max_iters = 1000
batch_size = 100
w0 = np.zeros(tXs.shape[1])
gamma = 0.1

ls_mse, w_ls = least_squares(ys, tXs)
gdls_mse, w_gdls = least_squares_GD_auto(ys, tXs, max_iters, w0)
sgdls_mse, w_sgdls = least_squares_SGD_simple(ys, tXs, max_iters, batch_size, w0, gamma)

In [10]:
ls_mse, w_ls

(0.080860029136592723,
 array([  6.19262784e-01,  -3.48254381e-03,  -2.00669630e-01,
         -2.60510267e-01,   1.25051152e-01,  -5.16690891e+01,
          1.14947912e+00,  -3.25619614e+00,   2.65925968e-01,
         -1.28704959e-02,  -2.51140179e+02,  -9.88839522e-03,
          6.02796865e-02,   6.04582638e+01,   4.90322633e+01,
          1.44128890e-02,   1.71586339e-02,   4.80751966e+01,
          1.42073082e-02,   1.79759768e-02,   1.10351021e-01,
          1.28078416e-02,  -2.49591704e-02,  -1.01030590e-01,
         -5.83804524e-02,  -8.61207727e-01,   9.59726966e-01,
         -1.15020157e+00,  -2.96211017e+00,  -2.26912268e+00,
          2.12680338e+02]))

In [11]:
gdls_mse, w_gdls

(0.081090094634570301,
 array([ 0.61749087, -0.00350895, -0.20033792, -0.26202847,  0.12719733,
        -0.09113578,  0.86489901, -0.1051342 ,  0.26675069, -0.01341465,
         0.03105237, -0.00945033,  0.0596616 , -0.09290793,  0.38227467,
         0.01393942,  0.01687884,  0.1784187 ,  0.01385662,  0.01756573,
         0.11131028,  0.01250298, -0.02464514, -0.10994267,  0.01831884,
         0.01313335,  0.01557331, -0.09929778, -0.09599082, -0.09546416,
        -0.09091669]))

In [12]:
sgdls_mse, w_sgdls

(0.082362831309290577,
 array([ 0.60448291,  0.00934108, -0.21317646, -0.1922969 ,  0.0879337 ,
        -0.0344858 ,  0.45262074, -0.04375892,  0.23290884, -0.02794791,
         0.05733164, -0.02020582,  0.06437941, -0.03690732,  0.32894465,
         0.00295182,  0.01854217,  0.15126176,  0.00730847,  0.01309575,
         0.12503352,  0.00753471, -0.02478818, -0.1114413 ,  0.01192941,
         0.0084104 ,  0.0087273 , -0.03550114, -0.03761911, -0.03775579,
        -0.04158819]))

## Ridge regression

In [13]:
from ridge_regression import ridge_regression, ridge_regression_auto

lambdas = np.logspace(-4, 2, 10)
kfold=4

ridge_mse, w_ridge = ridge_regression(ys, tXs, 0.5)
ridge_kfold_mse, w_ridge_kfold = ridge_regression_auto(ys, tXs, kfold, lambdas)

In [14]:
ridge_mse, w_ridge

(0.081059862864771473,
 array([ 0.6176896 , -0.00362256, -0.20011199, -0.2620972 ,  0.12490116,
        -2.51668155,  0.91120865,  1.48549208,  0.26692442, -0.01337131,
         0.02365173, -0.00982458,  0.05974819,  1.3620162 ,  0.38322741,
         0.01411646,  0.01711299,  0.17982258,  0.01403886,  0.01788381,
         0.11081732,  0.01277147, -0.02399423, -0.09282145,  0.13531996,
        -0.5642955 ,  0.47548269, -0.33596424, -0.46838878, -0.15653502,
        -0.09865429]))

In [15]:
ridge_kfold_mse, w_ridge_kfold

(0.081519485506405504,
 array([ 0.61488771, -0.00220356, -0.19810031, -0.25308542,  0.12966762,
        -0.09105782,  0.83208684, -0.08624911,  0.26201054, -0.01512015,
         0.03038207, -0.00886324,  0.06090434, -0.08116381,  0.37753778,
         0.01423132,  0.01639259,  0.17039453,  0.01396775,  0.01694925,
         0.10690022,  0.01184873, -0.02470014, -0.10277612,  0.03752259,
        -0.00313824,  0.0080952 , -0.11736083, -0.09032999, -0.0890103 ,
        -0.08880662]))

## Logistic regression

In [16]:
from logistic_regression import logistic_regression, reg_logistic_regression

#NOTE: loss here is different (includes log terms) so it will differ from mse above

gamma=0.1
max_iters = 1000
lambda_= 0.1

#IMPORTANT: it is probably better to use ONLY the regularized version of log_regression for this
#dataset as the Newton method depends on the hessian being non-singular (which is guaranteed by lambda_>0)
lreg_reg_loss, w_lreg_reg = reg_logistic_regression(ys, tXs, lambda_, gamma, max_iters)

In [ ]:
lreg_reg_loss, w_lreg_reg

(120697.62379056646,
 array([-1.42437243,  0.37250451, -1.01116998, -2.32468518,  1.21154496,
        -4.44274888,  3.53783789,  1.72279415,  2.11202366, -0.24577824,
        -0.65038316, -1.45310609,  0.19917875,  3.1290064 ,  1.42673614,
        -0.01635715, -0.0425736 ,  2.05350907, -0.01064965, -0.02422896,
         0.12833818, -0.03040323, -0.10600138, -0.52151386,  6.72279047,
        -0.94788215, -4.81754351,  2.2045548 , -0.94393173, -3.82393953,
        -1.55245044]))

In [ ]:
from logistic_regression import reg_logistic_regression_auto

max_iters = 1000
lambdas = np.logspace(-5, 3, 15)
kfold=10

logreg_auto_loss, w_logreg_auto = reg_logistic_regression_auto(ys, tXs, kfold, max_iters, lambdas)

In [ ]:
logreg_auto_loss, w_logreg_auto

In [ ]:
weights_log = w_logreg_auto

In [ ]:
weights_ls = w_ridge_kfold

## Generate predictions and save ouput in csv format for submission:

In [4]:
DATA_TEST_PATH = '../test.csv' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [31]:
OUTPUT_PATH_LS = '../submission_ls.csv' # TODO: fill in desired name of output file for submission
OUTPUT_PATH_LOG = '../submission_log.csv'

y_pred_ls = predict_labels(weights_ls, tX_test)
y_pred_log = predict_labels(weights_log, tX_test)
create_csv_submission(ids_test, y_pred_ls, OUTPUT_PATH_LS)
create_csv_submission(ids_test, y_pred_log, OUTPUT_PATH_LOG)