In [32]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Load the training data into feature matrix, class labels, and event ids:

In [33]:
from proj1_helpers import *
from helpers import *

DATA_TRAIN_PATH = '../train.csv' 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)
y[y==-1]=0

In [34]:
ys, tXs = y, tX

In [35]:
#Optional: normalize rows
row_sums = tXs.max(axis=1)
tXs = tXs / row_sums[:, np.newaxis]

In [36]:
tXs,_,_= standardize(tXs)

In [6]:
tXs.shape

(250000, 31)

In [7]:
ys.shape

(250000,)

In [8]:
ys

array([ 1.,  0.,  0., ...,  1.,  0.,  0.])

# Crazy Machine Learning

## Baselines (all methods should get similar estimates of w and mse)

## Fit with Least squares

In [9]:
from least_squares import least_squares
from least_squares import least_squares_GD_auto, least_squares_SGD_simple
max_iters = 1000
batch_size = 100
w0 = np.zeros(tXs.shape[1])
gamma = 0.1

ls_mse, w_ls = least_squares(ys, tXs)
gdls_mse, w_gdls = least_squares_GD_auto(ys, tXs, max_iters, w0)
sgdls_mse, w_sgdls = least_squares_SGD_simple(ys, tXs, max_iters, batch_size, w0, gamma)

In [10]:
ls_mse, w_ls

(0.080860029136592723,
 array([  6.19262784e-01,  -3.48254381e-03,  -2.00669630e-01,
         -2.60510267e-01,   1.25051152e-01,  -5.16690891e+01,
          1.14947912e+00,  -3.25619614e+00,   2.65925968e-01,
         -1.28704959e-02,  -2.51140179e+02,  -9.88839522e-03,
          6.02796865e-02,   6.04582638e+01,   4.90322633e+01,
          1.44128890e-02,   1.71586339e-02,   4.80751966e+01,
          1.42073082e-02,   1.79759768e-02,   1.10351021e-01,
          1.28078416e-02,  -2.49591704e-02,  -1.01030590e-01,
         -5.83804524e-02,  -8.61207727e-01,   9.59726966e-01,
         -1.15020157e+00,  -2.96211017e+00,  -2.26912268e+00,
          2.12680338e+02]))

In [11]:
gdls_mse, w_gdls

(0.081090094634570301,
 array([ 0.61749087, -0.00350895, -0.20033792, -0.26202847,  0.12719733,
        -0.09113578,  0.86489901, -0.1051342 ,  0.26675069, -0.01341465,
         0.03105237, -0.00945033,  0.0596616 , -0.09290793,  0.38227467,
         0.01393942,  0.01687884,  0.1784187 ,  0.01385662,  0.01756573,
         0.11131028,  0.01250298, -0.02464514, -0.10994267,  0.01831884,
         0.01313335,  0.01557331, -0.09929778, -0.09599082, -0.09546416,
        -0.09091669]))

In [12]:
sgdls_mse, w_sgdls

(0.082362831309290577,
 array([ 0.60448291,  0.00934108, -0.21317646, -0.1922969 ,  0.0879337 ,
        -0.0344858 ,  0.45262074, -0.04375892,  0.23290884, -0.02794791,
         0.05733164, -0.02020582,  0.06437941, -0.03690732,  0.32894465,
         0.00295182,  0.01854217,  0.15126176,  0.00730847,  0.01309575,
         0.12503352,  0.00753471, -0.02478818, -0.1114413 ,  0.01192941,
         0.0084104 ,  0.0087273 , -0.03550114, -0.03761911, -0.03775579,
        -0.04158819]))

## Ridge regression

In [37]:
from ridge_regression import ridge_regression, ridge_regression_auto

lambdas = np.logspace(-4, 2, 10)
kfold=4

ridge_mse, w_ridge = ridge_regression(ys, tXs, 0.5)
ridge_kfold_mse, w_ridge_kfold = ridge_regression_auto(ys, tXs, kfold, lambdas)

In [38]:
ridge_mse, w_ridge

(0.084338419697090022,
 array([  3.42667315e-01,  -2.48940677e-02,  -1.87680407e-01,
         -2.08467263e-01,   1.99183952e-02,  -2.08148101e+00,
          9.40649031e-01,   2.01215133e+00,   2.64751018e-01,
         -1.49863501e-02,   3.66952090e-02,  -6.60167663e-02,
          3.34235282e-02,   1.35291344e+00,   1.37807891e-01,
          1.02087026e-03,  -4.53907328e-04,   1.12964732e-01,
         -2.85992386e-04,   5.00546006e-04,   5.33922076e-02,
         -7.50055512e-04,  -4.28039120e-02,  -1.23804869e-01,
          6.30566927e-01,  -6.15266050e-02,  -4.09253809e-01,
         -1.86952547e+00,   1.75633978e-01,  -3.54930287e-01,
         -8.89847886e-02]))

In [39]:
ridge_kfold_mse, w_ridge_kfold

(0.084699623611429339,
 array([  3.42219522e-01,  -2.64856674e-02,  -1.85776978e-01,
         -2.13196914e-01,   2.63477858e-02,  -5.70440482e-02,
          6.26439529e-01,  -5.52562231e-02,   2.64770305e-01,
         -1.73391502e-02,   3.83944471e-02,  -6.45723565e-02,
          3.39353811e-02,  -5.07791709e-02,   1.37308973e-01,
          1.23762736e-03,  -7.48197114e-04,   1.06693577e-01,
         -3.82245277e-04,   7.65432579e-05,   4.98488396e-02,
         -1.08354113e-03,  -5.20968759e-02,  -1.35172210e-01,
          1.56404616e-01,   7.98005992e-03,   6.64787596e-03,
         -1.88468179e-01,  -5.68719683e-02,  -6.02392962e-02,
         -8.65782472e-02]))

## Logistic regression

In [40]:
from logistic_regression import logistic_regression, reg_logistic_regression

#NOTE: loss here is different (includes log terms) so it will differ from mse above

gamma=0.1
max_iters = 1000
lambda_= 0.1

#IMPORTANT: it is probably better to use ONLY the regularized version of log_regression for this
#dataset as the Newton method depends on the hessian being non-singular (which is guaranteed by lambda_>0)
lreg_reg_loss, w_lreg_reg = reg_logistic_regression(ys, tXs, lambda_, gamma, max_iters)

In [41]:
lreg_reg_loss, w_lreg_reg

(122544.69129827122,
 array([ -1.07686643e+00,   1.02085284e-01,  -8.75814010e-01,
         -1.62279888e+00,   2.42056216e-01,  -2.73753671e+00,
          3.33691672e+00,   5.69404715e+00,   2.34785883e+00,
         -7.06138640e-02,   3.72435984e-01,  -9.94627222e-01,
          1.26062111e-01,   4.86798274e+00,   5.86799857e-01,
          5.10846359e-03,  -2.40351825e-03,   1.02489366e+00,
          1.57881455e-04,   5.27267271e-03,   1.61615537e-01,
         -4.46485280e-03,  -2.10016127e-01,  -9.37010896e-01,
         -8.03358868e-01,   1.66325083e+00,   3.11412860e-01,
         -1.19691867e+01,   1.75356051e+00,   3.25515774e-01,
         -4.82966734e-01]))

In [42]:
from logistic_regression import reg_logistic_regression_auto

max_iters = 1000
lambdas = np.logspace(-5, 3, 15)
kfold=10

logreg_auto_loss, w_logreg_auto = reg_logistic_regression_auto(ys, tXs, kfold, max_iters, lambdas)

In [43]:
logreg_auto_loss, w_logreg_auto

(12708.745116034943,
 array([-0.87598563,  0.22764919, -0.79292693, -0.62935127,  0.13063614,
         0.04528145,  0.18473945,  0.04298838,  0.75497281, -0.10883116,
         0.1318357 , -0.3929529 ,  0.19492078,  0.04491541,  0.53224663,
         0.00249022, -0.00656369,  0.25894215,  0.00479075,  0.00562778,
         0.08440271, -0.00701041, -0.2823877 , -0.35697111,  0.12071453,
         0.11360302,  0.11350984,  0.03332159,  0.04442074,  0.04426192,
        -0.26632662]))

In [44]:
weights_log = w_logreg_auto

In [45]:
weights_ls = w_ridge_kfold

## Generate predictions and save ouput in csv format for submission:

In [46]:
DATA_TEST_PATH = '../test.csv' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)
#Optional: normalize rows
row_sums = tX_test.max(axis=1)
tX_test = tX_test / row_sums[:, np.newaxis]

tX_test,_,_= standardize(tX_test)

In [47]:
tX_test.shape

(568238, 31)

In [48]:
OUTPUT_PATH_LS = '../submission_ls.csv' # TODO: fill in desired name of output file for submission
OUTPUT_PATH_LOG = '../submission_log.csv'

y_pred_ls = predict_labels(weights_ls, tX_test)
y_pred_log = predict_labels_logistic(weights_log, tX_test)


In [49]:
print(y_pred_ls)
print(y_pred_log)

[-1.  1.  1. ...,  1.  1. -1.]
[-1. -1. -1. ...,  1.  1. -1.]


In [50]:
print(y_pred_ls.shape)
print(y_pred_log.shape)

(568238,)
(568238,)


In [51]:
create_csv_submission(ids_test, y_pred_ls, OUTPUT_PATH_LS)
create_csv_submission(ids_test, y_pred_log, OUTPUT_PATH_LOG)