In [92]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Load the training data into feature matrix, class labels, and event ids:

In [146]:
from proj1_helpers import *
from helpers import *

DATA_TRAIN_PATH = '../train_pca.csv' 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)
y[y==-1]=0

In [147]:
ys, tXs = y, tX

In [148]:
#Optional: normalize rows
#row_sums = tXs.max(axis=1)
#tXs = tXs / row_sums[:, np.newaxis]

In [149]:
tXs,_,_= standardize(tXs)

In [150]:
tXs.shape

(250000, 31)

In [151]:
ys.shape

(250000,)

In [152]:
ys

array([ 1.,  0.,  0., ...,  1.,  0.,  0.])

In [153]:
tXs

array([[ 1.        ,  0.46242658, -1.37398346, ...,  1.56537312,
         1.5653623 ,  0.6306402 ],
       [ 1.        ,  0.51367613, -0.4961084 , ..., -0.63825412,
        -0.63825413, -0.30574226],
       [ 1.        , -2.33946272,  2.05729923, ..., -0.64532598,
        -0.64531484,  0.21581095],
       ..., 
       [ 1.        ,  0.37934952, -0.35765339, ..., -0.63795934,
        -0.63795899, -0.26076957],
       [ 1.        ,  0.35670547, -0.00535578, ..., -0.63730215,
        -0.63730533, -0.93318754],
       [ 1.        , -2.33532248,  2.08060995, ..., -0.63942504,
        -0.63941597, -0.81528111]])

# Crazy Machine Learning

## Baselines (all methods should get similar estimates of w and mse)

## Fit with Least squares

In [65]:
from least_squares import least_squares
from least_squares import least_squares_GD_auto, least_squares_SGD_simple
max_iters = 1000
batch_size = 100
w0 = np.zeros(tXs.shape[1])
gamma = 0.1

ls_mse, w_ls = least_squares(ys, tXs)
gdls_mse, w_gdls = least_squares_GD_auto(ys, tXs, max_iters, w0)
sgdls_mse, w_sgdls = least_squares_SGD_simple(ys, tXs, max_iters, batch_size, w0, gamma)

KeyboardInterrupt: 

In [9]:
ls_mse, w_ls

(0.08486139962233244,
 array([  3.42668000e-01,   1.46894135e-02,  -1.26265738e-01,
         -1.27395562e-01,  -1.51848412e-02,  -7.00723588e-01,
          1.47850821e-01,  -5.39447357e+00,   1.33940431e-01,
         -1.22467489e-03,  -1.64408736e+02,  -9.13239441e-02,
          5.70198133e-02,   1.02522980e+01,   3.19416930e+01,
         -1.59480956e-04,  -9.04421480e-04,   3.14962841e+01,
         -2.24320729e-04,   7.71896441e-04,   6.07313503e-02,
          1.97634414e-04,  -3.16611736e-02,  -1.03373547e-01,
         -5.83278849e-02,   4.93128226e-02,   8.39538546e-02,
         -1.67573128e-02,  -1.49179344e+00,  -2.68194046e+00,
          1.39235199e+02]))

In [10]:
gdls_mse, w_gdls

(0.085006007482485935,
 array([  3.42668000e-01,   1.45632449e-02,  -1.26738913e-01,
         -1.27530067e-01,  -1.54917793e-02,  -1.20909570e-02,
          2.09016254e-01,  -1.98401722e-02,   1.33953007e-01,
         -1.00754405e-03,  -4.04023001e-04,  -9.13110485e-02,
          5.75444913e-02,  -1.36777979e-02,   9.62282138e-02,
         -3.20291370e-04,  -5.34745366e-04,   1.44148765e-01,
         -4.47812519e-04,   1.27149540e-03,   6.05219879e-02,
          5.17684433e-04,  -3.15704551e-02,  -9.37837120e-02,
          2.22635189e-02,   2.76892737e-02,   2.76875391e-02,
         -1.42745900e-02,  -1.48432129e-02,  -1.51770128e-02,
         -5.49301899e-02]))

In [11]:
sgdls_mse, w_sgdls

(0.086670130876927653,
 array([ 0.34254363,  0.00679056, -0.12437178, -0.12596976, -0.03086418,
        -0.02350184,  0.20678933, -0.03220147,  0.1248132 , -0.01175256,
        -0.00063586, -0.07818721,  0.07096755, -0.02526131,  0.10278411,
        -0.00949337, -0.00084807,  0.13710221,  0.00447407,  0.00878808,
         0.04379585,  0.01167051, -0.0393092 , -0.09340691,  0.02852881,
         0.03260432,  0.03215285, -0.02855735, -0.02622768, -0.02656874,
        -0.05511662]))

## Ridge regression

In [154]:
from ridge_regression import ridge_regression, ridge_regression_auto

lambdas = np.logspace(-4, 2, 10)
kfold=4

ridge_mse, w_ridge = ridge_regression(ys, tXs, 0.5)
ridge_kfold_mse, w_ridge_kfold = ridge_regression_auto(ys, tXs, kfold, lambdas)

In [155]:
ridge_mse, w_ridge

(0.10120769446362254,
 array([ 0.34266731,  0.01615093, -0.02599998,  0.00669563, -0.00447669,
         0.00771486,  0.09096429,  0.00632838,  0.04758791, -0.05868137,
         0.00042059,  0.00649691,  0.03291953,  0.00727531, -0.00072294,
        -0.02820685, -0.0257552 , -0.01436889,  0.004901  ,  0.0630885 ,
        -0.01098818,  0.01546274, -0.01256624,  0.02523671,  0.01527609,
         0.01582051,  0.01582042,  0.00826428,  0.0071997 ,  0.00720249,
         0.00268969]))

In [156]:
ridge_kfold_mse, w_ridge_kfold

(0.10163173948487755,
 array([  3.41931196e-01,   1.60337439e-02,  -2.61207737e-02,
          6.57918203e-03,  -4.62069465e-03,   7.78742198e-03,
          9.20244668e-02,   6.38445837e-03,   4.79974539e-02,
         -5.94650692e-02,   3.33074133e-04,   6.50135839e-03,
          3.31587081e-02,   7.34269119e-03,  -8.78717898e-04,
         -2.85631061e-02,  -2.58251769e-02,  -1.46707018e-02,
          4.87428093e-03,   6.38208323e-02,  -1.10487140e-02,
          1.54217223e-02,  -1.28246187e-02,   2.54653576e-02,
          1.54353164e-02,   1.59927317e-02,   1.59926471e-02,
          8.34053199e-03,   7.26619668e-03,   7.26902544e-03,
          2.64769629e-03]))

## Logistic regression

In [157]:
from logistic_regression import logistic_regression, reg_logistic_regression

#NOTE: loss here is different (includes log terms) so it will differ from mse above

gamma=0.1
max_iters = 1000
lambda_= 0.1

#IMPORTANT: it is probably better to use ONLY the regularized version of log_regression for this
#dataset as the Newton method depends on the hessian being non-singular (which is guaranteed by lambda_>0)
lreg_reg_loss, w_lreg_reg = reg_logistic_regression(ys, tXs, lambda_, gamma, max_iters)

In [158]:
lreg_reg_loss, w_lreg_reg

(146247.89608309485,
 array([-0.75424655,  0.12803078, -0.16901247,  0.0517195 , -0.02411886,
         0.04044017,  0.48461035,  0.03303999,  0.27181598, -0.31543273,
         0.00182759,  0.0312122 ,  0.18951844,  0.0380941 ,  0.00140733,
        -0.15150026, -0.17514237, -0.07378615,  0.03355376,  0.33183968,
        -0.08144831,  0.10872459, -0.0658675 ,  0.13263325,  0.07849072,
         0.08133725,  0.08133655,  0.04335279,  0.03769044,  0.03770514,
         0.0127192 ]))

In [159]:
from logistic_regression import reg_logistic_regression_auto

max_iters = 1000
lambdas = np.logspace(-5, 3, 15)
kfold=10

logreg_auto_loss, w_logreg_auto = reg_logistic_regression_auto(ys, tXs, kfold, max_iters, lambdas)

In [160]:
logreg_auto_loss, w_logreg_auto

(14717.002587926771,
 array([-0.75600125,  0.1283613 , -0.16978004,  0.05182303, -0.02456245,
         0.04067401,  0.48803818,  0.03322059,  0.27362152, -0.31784431,
         0.00161907,  0.03135987,  0.19040142,  0.03831125,  0.00117053,
        -0.15293348, -0.176071  , -0.07452454,  0.03334672,  0.33423387,
        -0.08193677,  0.10896689, -0.06658042,  0.13333743,  0.07873525,
         0.08160385,  0.08160319,  0.04360469,  0.03790458,  0.03791934,
         0.01260376]))

In [161]:
weights_log = w_logreg_auto

In [162]:
weights_ls = w_ridge_kfold

In [163]:
weights_log

array([-0.75600125,  0.1283613 , -0.16978004,  0.05182303, -0.02456245,
        0.04067401,  0.48803818,  0.03322059,  0.27362152, -0.31784431,
        0.00161907,  0.03135987,  0.19040142,  0.03831125,  0.00117053,
       -0.15293348, -0.176071  , -0.07452454,  0.03334672,  0.33423387,
       -0.08193677,  0.10896689, -0.06658042,  0.13333743,  0.07873525,
        0.08160385,  0.08160319,  0.04360469,  0.03790458,  0.03791934,
        0.01260376])

In [164]:
weights_ls

array([  3.41931196e-01,   1.60337439e-02,  -2.61207737e-02,
         6.57918203e-03,  -4.62069465e-03,   7.78742198e-03,
         9.20244668e-02,   6.38445837e-03,   4.79974539e-02,
        -5.94650692e-02,   3.33074133e-04,   6.50135839e-03,
         3.31587081e-02,   7.34269119e-03,  -8.78717898e-04,
        -2.85631061e-02,  -2.58251769e-02,  -1.46707018e-02,
         4.87428093e-03,   6.38208323e-02,  -1.10487140e-02,
         1.54217223e-02,  -1.28246187e-02,   2.54653576e-02,
         1.54353164e-02,   1.59927317e-02,   1.59926471e-02,
         8.34053199e-03,   7.26619668e-03,   7.26902544e-03,
         2.64769629e-03])

## Generate predictions and save ouput in csv format for submission:

In [165]:
DATA_TEST_PATH = '../test_pca.csv' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)
#Optional: normalize rows
#row_sums = tX_test.max(axis=1)
#tX_test = tX_test / row_sums[:, np.newaxis]

tX_test,_,_= standardize(tX_test)

In [166]:
tX_test.shape

(568238, 31)

In [167]:
OUTPUT_PATH_LS = '../submission_ls.csv' # TODO: fill in desired name of output file for submission
OUTPUT_PATH_LOG = '../submission_log.csv'

y_pred_ls = predict_labels(weights_ls, tX_test)
y_pred_log = predict_labels_logistic(weights_log, tX_test)


In [168]:
print(y_pred_ls)
print(y_pred_log)

[ 1.  1.  1. ...,  1.  1.  1.]
[-1. -1. -1. ..., -1. -1. -1.]


In [169]:
print(y_pred_ls.shape)
print(y_pred_log.shape)

(568238,)
(568238,)


In [170]:
create_csv_submission(ids_test, y_pred_ls, OUTPUT_PATH_LS)
create_csv_submission(ids_test, y_pred_log, OUTPUT_PATH_LOG)